# Generated by Django 3.2.16 on 2024-06-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jitterbunk', '0002_auto_20240612_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunk',
            name='time',
            field=models.TimeField(),
        ),
    ]
